### ISSUE TITLE
logs off immediately

### ISSUE THREAD

**Issue by appsdevpk** [nopwdio/sdk-js#9]
just tried the sample code for login, works perfectly, until i clicked on login link in email, it took me to the site, shows green logged in button for 2 seconds and immediately logged out and then displayed the login button.

```
<np-email-auth lifetime="604800" idletimeout="86400">
Login
<span slot="requesting">Sending email...</span>
<span slot="requested">Check your mailbox</span>
<span slot="error">Oooooops</span>
</np-email-auth>

<script type="module">
const button = document.querySelector("np-email-auth");
button.email = "me@email.com";
console.log(button);
button.addEventListener("np:login", (e) => {
	const { expires_at, token } = e.detail;
	console.log(e.detail);
});
</script>
```

**Comment by apinet** [comment]
Hello, first of all, thank you for your interest in this service.

The `<np-email-auth>` component emits the `np:login` event to indicate to the web page that the authentication has been successful. It is then up to this same web page to either redirect to the connected environment or adapt the current page to display the logout button `<np-logout>` instead.

The component resets its state even if a user is already connected (which is the case in your example). We do acknowledge that this behavior can be confusing and will maintain the connected state for this button.

We will fix this for the next release.

Thank you again for your feedback.

Adrien
